### ISSUE TITLE
missing the word 'not'

### ISSUE THREAD

**Issue by DrAlta** [ReuthMirsky/Standardization-Project#1]
"Their code is available online, soon will be able to handle parameters."

You meant "Their code is not available online, soon will be able to handle parameters." didn't you.

**Comment by ReuthMirsky** [comment]
That was the comment from SBR's authors.
Anyway, there is an implementation of SBR as part of this project. Mainly, https://github.com/ReuthMirsky/Standardization-Project/blob/master/SBR-CSQ.zip
